SELECT p.PRODUCT_CODE, (PRICE * os.AMOUNT) SALES
FROM PRODUCT p
LEFT JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) os
ON p.PRODUCT_ID = os.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE