SELECT p.PRODUCT_ID, 
       p.PRODUCT_NAME, 
       o.AMOUNT * p.PRICE TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN (
    SELECT PRODUCT_ID, 
           SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE <  '2022-06-01'
    GROUP BY PRODUCT_ID
) o
ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY 3 DESC, 1 