SELECT u.USER_ID, u.NICKNAME, p.TOTAL_SALES
FROM USED_GOODS_USER u 
JOIN (SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
      FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE'
      GROUP BY 1) p
ON u.USER_ID = p.WRITER_ID
WHERE TOTAL_SALES >= 700000 
ORDER BY 3