SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT *, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) rnk
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN('과자', '국', '김치', '식용유')
) t
WHERE rnk = 1
ORDER BY MAX_PRICE DESC